# Generated by Django 3.0.dev20190421104733 on 2019-11-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Studienrichtung')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Fachbezeichung')),
                ('major_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lvtool.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('m_nr', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Matrikelnummer')),
                ('first_name', models.CharField(max_length=20, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=20, verbose_name='Nachname')),
                ('major_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lvtool.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(max_length=4, primary_key=True, serialize=False, verbose_name='LV-Nummer')),
                ('time', models.TimeField(verbose_name='Uhrzeit')),
                ('date', models.DateField(verbose_name='Datum')),
                ('lecturer', models.CharField(max_length=40, verbose_name='Dozent')),
                ('subject_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lvtool.Subject')),
            ],
        ),
    ]
