# Generated by Django 3.0.dev20190421104733 on 2019-11-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default='18:30', verbose_name='Uhrzeit Ende'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.TimeField(verbose_name='Uhrzeit Beginn'),
        ),
    ]
