# Generated by Django 2.2.8 on 2019-12-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvplaner', '0002_auto_20191125_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='LV-Nummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='m_nr',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrikelnummer'),
        ),
    ]
